apiVersion: v1
kind: PersistentVolume
metadata:
  name: file-storage
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: file-storage
  hostPath:
    path: /Users/ruihirano/MyProjects/Map4Projects/map4_engine_web/file_storage
    type: DirectoryOrCreate

---

  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: pv-file-storage-claim
  spec:
    accessModes:
      - ReadWriteOnce
    volumeMode: Filesystem
    resources:
      requests:
        storage: 1Gi
    storageClassName: file-storage
