project_name: dqn_breakout_20200511
type: train # train or eval or retrain
env_param: 
    env_name: BreakoutNoFrameskip-v4
    episode_life: True
    clip_rewards: False
    frame_stack: True
    scale: False
    seed_num: 1
brain_param: 
    batch_size: 32
    gamma: 0.99
    eps_start: 1.0
    eps_end: 0.1
    eps_decay: 200
    capacity: 200000
    hidden_size: 100
    optimizer_name: RMSProp
    learning_rate: 0.0005
    prioritized: True # 優先度付き経験再生にするかどうか
    dueling: True # DuelingNetにするかどうか
    eps: 0.00005
train_param:
    save_path: "./result/dqn_breakout_20200511"
    episode_num: 100000
    record_iter: 1000 # 1000episodeごとにweightを保存
    target_update_iter: 10 # 100episodeごとにtargetをupdate
    save_name: dqn_breakout_20200511
eval_param:
    save_path: "./result/dqn_breakout_20200511"
    weights_name: dqn_breakout_20200511_1000.pth
    episode_num: 100